name: Deploy Vue to Cloud Run

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Decode Service Account Key
      run: echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > gcp-key.json

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ github.workspace }}/gcp-key.json

    - name: Configure Docker
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.IMAGE_NAME }} .
        docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.IMAGE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vue-frontend \
          --image=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.IMAGE_NAME }} \
          --region=${{ secrets.GCP_REGION }} \
          --platform=managed \
          --allow-unauthenticated
